version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    CLUSTER_NAME: cluster1
    REPOSITORY_URI: 043309347290.dkr.ecr.us-east-1.amazonaws.com/vikram

phases:
  pre_build:
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Image tag:$IMAGE_TAG"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
    - echo "Pushing Docker image to ECR..."
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo "Updating kubeconfig for EKS..."
    - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
    - echo "Replacing image in deployment.yaml..."
    - sed -i "s|IMAGE_PLACEHOLDER|$REPOSITORY_URI:$IMAGE_TAG|g" deployment.yaml
    - echo "Applying deployment.yaml..."
    - kubectl apply -f deployment.yaml || (echo "❌ Failed to apply deployment.yaml" && exit 1)
    - echo "Applying service.yaml..."
    - kubectl apply -f service.yaml || (echo "❌ Failed to apply service.yaml" && exit 1)

artifacts:
  files:
    - imagedefinitions.json

