version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    CLUSTER_NAME: cluster1
    REPOSITORY_URI: 043309347290.dkr.ecr.us-east-1.amazonaws.com/vikram

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "Image tag:$IMAGE_TAG"

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
    post_build:
      commands:
    - echo "Pushing Docker image to ECR..."
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo "Updating kubeconfig for EKS..."
    - aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME
    - echo "Replacing image in deployment.yaml..."
    - sed -i "s|IMAGE_PLACEHOLDER|$REPOSITORY_URI:$IMAGE_TAG|g" deployment.yaml
    - echo "Applying deployment.yaml..."
    - cat deployment.yaml
    - kubectl apply -f deployment.yaml || (echo "❌ kubectl apply failed with exit code $?"; exit 1)


      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml

artifacts:
  files:
    - imagedefinitions.json

