apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-clone
spec:
  replicas: 10
  selector:
    matchLabels:
      app: instagram-clone
  template:
    metadata:
      labels:
        app: instagram-clone
    spec:
      containers:
        - name: instagram-clone
          image: 043309347290.dkr.ecr.us-east-1.amazonaws.com/vikram
