apiVersion: apps/v1
kind: Deployment
metadata:
  name: instagram-clone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: instagram-clone
  template:
    metadata:
      labels:
        app: instagram-clone
    spec:
      containers:
        - name: instagram-clone
          image: IMAGE_PLACEHOLDER  # This will be replaced
          ports:
            - containerPort: 3000  # Change this to your actual app port

