apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/vikram/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 07 May 2025 16:09:25 IST
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: cluster_info
    server: https://127.0.0.1:32776
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 07 May 2025 16:09:25 IST
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/vikram/.minikube/profiles/minikube/client.crt
    client-key: /home/vikram/.minikube/profiles/minikube/client.key
