apiVersion: v1
kind: Service
metadata:
  name: instagram-service
  labels:
    app: instagram-clone
spec:
  type: LoadBalancer  # Use ClusterIP for internal apps
  selector:
    app: instagram-clone
  ports:
    - protocol: TCP
      port: 80           # Exposed port (browser uses this)
      targetPort: 3000   # The port your container app listens on

